# TensorFlow
### Deep Learning
### Neural Networks
### 环境搭建详细教程
- Windows 10
- Ubuntu 18.04/16.04/20.04
- TensorFlow
- PyTorch
- CUDA cuDNN
- Jupyter Lab & Jupyter Notebook
- PyCharm

[环境搭建详细教程——GitHub-Blog](https://2694048168.github.io/)

[环境搭建详细教程——Gitee-Blog](http://weili_yzzcq.gitee.io/)

[环境搭建详细教程——CSDN-Blog](https://blog.csdn.net/weixin_46782218)


In [6]:
# 线性回归
# make decisions: discrete 离散值     continuous 连续值
# continuous prediction：input data（x）；prediction（f，参数 θ theta）；real data，ground-truth（y）
# linear equation 线性方程组 y = w * x + b + epsilon
# with noise  epsilon 噪声 高斯分布
# find the W and b
# loss = (WX + b - Y)**2
# miniize loss 
# gradient descent GD 梯度下降 一维和二维可视化
# loss surface
# linear regression
# logistic regression
# classification

import numpy as np

# 生成 csv 文件里面的数据
# data = []
# for i in range(100):
# 	x = np.random.uniform(3., 12.)
# 	# mean=0, std=0.1
# 	eps = np.random.normal(0., 0.1)
# 	y = 1.477 * x + 0.089 + eps
# 	data.append([x, y])
# data = np.array(data)
# print(data.shape, data)

# cpmputer loss
# Y = W*X +b
def computer_error_for_line_given_points(b, w, points):
    total_error = 0
    for i in range(0, len(points)):
        x = points[i, 0]
        y = points[i, 1]
        # computer mean-squared-error
        total_error += ((w * x + b) - y) ** 2
        # total_error += (y - (w * x + b)) ** 2
    # average loss for each point
    return total_error / float(len(points))

# computer Gradient and update
def step_gradient(b_current, w_current, points, learning_rate):
    b_gradient = 0
    w_gradient = 0
    N = float(len(points))
    for i in range(0, len(points)):
        x = points[i, 0]
        y = points[i, 1]
        # grad_b = 2(wx + b - y)
        b_gradient += (2/N) * ((w_current * x + b_current) - y)
        # grad_w = 2(wx + b - y) * x
        w_gradient += (2/N) * x * ((w_current * x + b_current) - y)
    # update the grad_w, and the grad_b
    new_b = b_current - (learning_rate * b_gradient)
    new_w = w_current - (learning_rate * w_gradient)
    return [new_b, new_w]

# set w = w_new and loop
def gradient_descent_runner(points, starting_b, starting_w, learning_rate, num_iterations):
    b = starting_b
    w = starting_w
    # update for several times
    for i in range(num_iterations):
        b, w = step_gradient(b, w, np.array(points), learning_rate)
    return [b, w]


# running the linear regression model
# loading the data for numpy from the data.cvs file
# the data shape is 100 * 2 (row * column)
points = np.genfromtxt("./datasets/data.csv", delimiter=",")
# init the Hyperparameter
learning_rate = 0.0001
initial_b = 0
initial_w = 0
num_iterations = 1000
# show the initial Hyperparameter for linear regression model and the error
print("Starting gradient descent at b = {0}, w = {1}, error = {2}"
      .format(initial_b, initial_w, computer_error_for_line_given_points(initial_b, initial_w, points)))

print("Running")
# iterations = 1000,computer the Hyperparameter for linear regression model
[b, w] = gradient_descent_runner(points, initial_b, initial_w, learning_rate, num_iterations)

# and show the Hyperparameter for linear regression model and the error
print("After {0} iterations b = {1}, w = {2}, error = {3}"
      .format(num_iterations, b, w, computer_error_for_line_given_points(b, w, points)))


Starting gradient descent at b = 0, w = 0, error = 5565.107834483211
Running
After 1000 iterations b = 0.08893651993741346, w = 1.4777440851894448, error = 112.61481011613473


In [13]:
# Image Classification
# hand-written digits recognition
# MNIST: 7,000 images per category = 70,000
# train / test splitting = 60k / 10k
# [28, 28, 1] = [rows,columns, gray_value]
# 28 * 28 = 784 转换为一维数组
# input and output
# coding the features for data: one-hot
# regression VS classification
# y = w * x + b
# y 属于空间 R^d
# out = X @ W + b
# out:[0.1, 0.8, 0.02,.0.08] = 1 概率，最大值概率称之为置信度
# pred = argmax(out)

# out = X @ W + b
# X = [b, 784]
# W = [784, 10]
# b = [10]

# it is linear !
# out = X @ W + b
# 变成 non-linear !
# out = f(X @ W + b)
# 引入非线性因子，这个 f 函数称之为激活函数，
# f = ReLu function and sigmoid function
# out = relu(X @ W + b)

# it is simple
# out = relu(X @ W + b)
# 添加隐藏层 hide layer
# h1 = relu(X @ W1 + b1)
# h2 = relu(X @ W2 + b2)
# out = relu(X @ W3 + b3)

# particularly
# 每一层都是类似降维的过程，直到从 [1, 784] ---- [1, 10]
# X = [v1, v2, ... , v784]
# h1 = relu(X @ W1 + b1)
#    W1: [784, 512]
#    b1: [1, 512]
# h2 = relu(X @ W2 + b2)
#    W2: [512, 256]
#    b2: [1, 256]
# out = relu(X @ W3 + b3)
#    W2: [256, 10]
#    b2: [1, 10]

# loss
# out:[1, 10]
# Y/label: 0-9 （one-hot）
# euclidean distance 计算欧式距离 使得 out 接近 label   MSE
# loss = (Y - out) **2

# in a nutshell
# out = relu{relu{relu[X @ W1 + b1] @ W2 + b2 } @ W3 + b3}
# pred = argmax(out)
# loss = MSE(out, label)
# minimize loss
# [w1_new, b2_new, w2_new, b2_new, w3_new, b3_new]

# Deep Learning
# classification precedure
# step1 compute [h1, h2, out]
# step2 compute loss
# step3 compute gradient and update [w1_new, b2_new, w2_new, b2_new, w3_new, b3_new]
# step4 loop
# need TensorFlow

# 以下两条语句，使得 TensorFlow 少打印出一些无关紧要的信息
# import  os
# os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

# step 0 loading data X and Y
import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets, layers, optimizers

(x, y), (x_val, y_val) = datasets.mnist.load_data() 
x = tf.convert_to_tensor(x, dtype=tf.float32) / 255.
y = tf.convert_to_tensor(y, dtype=tf.int32)
y = tf.one_hot(y, depth=10)
print(x.shape, y.shape)
train_dataset = tf.data.Dataset.from_tensor_slices((x, y))
# batch 概念
train_dataset = train_dataset.batch(200)
    
# step 0 model NN
model = tf.keras.Sequential([layers.Dense(512, activation="relu"),
                          layers.Dense(256, activation="relu"),
                          layers.Dense(10)])

optimizer = optimizers.SGD(learning_rate=0.001)

# 对整个训练集 训练 30 次，即就是 epoch = 30 
# 将训练集数据划分为每次读取 200 ，即就是 batch = 200
# 那么 step = train_data / batch = 60k / 200 = 300
# 每训练 100 个样本数据，就查看一次训练情况 loss
# 实际显示的 loss 情况次数 = epoch * (step / 100) = 30 * (300/100) = 90

# step4 loop
# 对一个数据集 dataset 训练一次称之为 epoch
def train_epoch(epoch):
    # 对一个 batch 训练一次称之为 step
    for step, (x, y) in enumerate(train_dataset):
        with tf.GradientTape() as tape:
            # [b， 28， 28] => [b, 784]
            x = tf.reshape(x, (-1, 28*28))
            # step 1 compute output
            # [b, 784] => [b, 10]
            out = model(x)
            # step2 compute loss
            loss = tf.reduce_sum(tf.square(out - y)) / x.shape[0]
            
        # step 3 optimize and update w1, w2, w3, b1, b2, b3
        grads = tape.gradient(loss, model.trainable_variables)
        # w_new = w - lr * grad
        optimizer.apply_gradients(zip(grads, model.trainable_variables)) 
        
        if step % 100 == 0:
            # print(epoch, step, 'loss:', loss.numpy())
            print("第 {0} 次 epoch，第 {1} step，该次训练 loss = {2}".format(epoch, step+100, loss.numpy()))

# 对整个数据集训练多次 30 次
for epoch in range(30):
    train_epoch(epoch)


(60000, 28, 28) (60000, 10)
0 0 2.145007
0 100 0.9779064
0 200 0.8011861
1 0 0.682101
1 100 0.68953323
1 200 0.59687996
2 0 0.5544969
2 100 0.60021234
2 200 0.5208171
3 0 0.49560317
3 100 0.5510172
3 200 0.4770015
4 0 0.45830703
4 100 0.51574916
4 200 0.44660082
5 0 0.4310113
5 100 0.48866108
5 200 0.42332447
6 0 0.40955436
6 100 0.46667328
6 200 0.40453193
7 0 0.3919871
7 100 0.44810033
7 200 0.38870093
8 0 0.37698773
8 100 0.4321654
8 200 0.3749433
9 0 0.3639257
9 100 0.41827995
9 200 0.3629041
10 0 0.35239592
10 100 0.40607452
10 200 0.35226172
11 0 0.34209
11 100 0.39520663
11 200 0.34277108
12 0 0.33278885
12 100 0.38533977
12 200 0.33422118
13 0 0.3244313
13 100 0.37634808
13 200 0.32637382
14 0 0.3167131
14 100 0.3681502
14 200 0.3191441
15 0 0.30964595
15 100 0.36062518
15 200 0.31245127
16 0 0.30311885
16 100 0.3536573
16 200 0.30619872
17 0 0.2970287
17 100 0.34722012
17 200 0.3003191
18 0 0.29140472
18 100 0.34124565
18 200 0.29482606
19 0 0.28617287
19 100 0.33563197
19 200

In [14]:
# TensorFlow 数据类型
# data container: list, np.array, tf.Tensor
# what is Tensor
# - scalar 标量 1.1
# - vector 向量 [1.1], [1.1, 2.2]
# - matrix 矩阵 [[1.1, 2.2], [3.3, 4.4], [5.5, 6.6]]
# - tensor rank > 2 矩阵的秩
# TF is a computing lib
# - int, float, double, bool, string

import tensorflow as tf

# create the int, float, double, bool, string
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [17]:
# tf.constant(1.2, dtype=tf.int32)
# TypeError: Cannot convert 1.2 to EagerTensor of dtype int32

In [18]:
tf.constant([True, False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [19]:
tf.constant("Hello World")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [27]:
# Tensor Property 常见属性
with tf.device("cpu"):
    const_cpu = tf.constant([1])

with tf.device("gpu"):
    const_gpu = tf.range(4)
    
# device 属性，查看 Tensor 在哪一个设备上 CPU or GPU
const_cpu.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [28]:
const_gpu.device
# 因为本地没有安装 GPU 加速驱动 CUDA 和 cuDNN
# 无法提供 GPU 加速环境，故此工作环境依旧还在 CPU 上

'/job:localhost/replica:0/task:0/device:CPU:0'

In [29]:
# 相互转换 
# const_cpu_to_gpu = const_cpu.gpu()
# const_cpu_to_gpu.device

const_gpu_to_cpu = tf.identity(const_gpu)
const_gpu_to_cpu.device

# tensor 的计算必须在同一设备进行，全部都是 CPU 或者全部都是 GPU

'/job:localhost/replica:0/task:0/device:CPU:0'

In [30]:
# numpy 属性，将 Tensor 转换为 numpy
# numpy 是在 CPU 上的
const_gpu.numpy()

array([0, 1, 2, 3])

In [31]:
# 查看 Tensor 的 shape 维度
# ndim 属性，返回 Tensor 的维度信息
# rank 方法，返回 Tensor 的维度信息
const_cpu.ndim

1

In [32]:
tf.rank(const_cpu)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [33]:
tf.rank(tf.ones([3, 2, 4]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [35]:
# 判断是否 Tensor
tf.is_tensor(const_cpu)


True

In [39]:
# 转换为 Tensor
const = np.arange(5)
const_tensor = tf.convert_to_tensor(const)
const_tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [36]:
# convert dtype
# 数值类型之间的转换
const_cpu.dtype

tf.int32

In [40]:
tf.cast(const_tensor, dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [41]:
tf.cast(const_tensor, dtype=tf.double)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [42]:
tf.cast(const_tensor, dtype=tf.int32)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [44]:
# int <==> bool
bool_num = tf.constant([0, 1])
bool_num_bool = tf.cast(bool_num, dtype=tf.bool)
bool_num_bool

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [45]:
tf.cast(bool_num_bool, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1])>

In [46]:
# tf.Variable
# 一般是需要优化的变量参数
a = tf.range(5)
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [47]:
b = tf.Variable(a)
b

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [48]:
b.dtype

tf.int32

In [49]:
b.name

'Variable:0'

In [51]:
b.trainable
# 需要梯度信息，可以自动求导
# 神经网络的参数需求

True

In [52]:
tf.is_tensor(b)

True

In [53]:
b.numpy()

array([0, 1, 2, 3, 4])