# the start of TensorFlow2 with MNIST

## Import TensorFlow into your program:

In [2]:
import tensorflow as tf

print("The version of TensorFlow in this source code: {}".format(tf.__version__))

The version of TensorFlow in this source code: 2.4.1


## Load and prepare the MNIST dataset. Convert the samples from integers to floating-point numbers:

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

## Build the tf.keras.Sequential model by stacking layers. Choose an optimizer and loss function for training:

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

## For each example the model returns a vector of "logits" or "log-odds" scores, one for each class.

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.4136075 ,  0.14655066, -0.14774564, -0.06394154,  0.10493204,
        -0.06326851, -0.26439154, -0.77751005,  0.19948927,  0.19039935]],
      dtype=float32)

## The tf.nn.softmax function converts these logits to "probabilities" for each class:

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.14858353, 0.11375995, 0.08475749, 0.09216665, 0.10912259,
        0.0922287 , 0.07542571, 0.04515178, 0.11994449, 0.11885915]],
      dtype=float32)

## The losses.SparseCategoricalCrossentropy loss takes a vector of logits and a True index and returns a scalar loss for each example.

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

## This loss is equal to the negative log probability of the true class: It is zero if the model is sure of the correct class.

## This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.383484

In [9]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

## The Model.fit method adjusts the model parameters to minimize the loss:

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4885 - accuracy: 0.8548
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1487 - accuracy: 0.9554
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1107 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0879 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0748 - accuracy: 0.9772


In [12]:
## The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".

In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0739 - accuracy: 0.9759


[0.0739322230219841, 0.9758999943733215]

## The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

## If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [14]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.7840500e-07, 5.6254137e-08, 4.6367927e-06, 2.2723593e-04,
        2.0170186e-10, 3.0349912e-07, 1.0412212e-14, 9.9972898e-01,
        2.0787847e-06, 3.6401736e-05],
       [3.4166145e-10, 3.6683690e-04, 9.9963224e-01, 8.5535191e-07,
        3.6665138e-17, 9.5843611e-10, 3.1257275e-09, 3.6692654e-12,
        6.0070768e-08, 9.3589820e-18],
       [2.5792681e-06, 9.9364108e-01, 1.3594751e-03, 7.6936034e-05,
        4.2264506e-05, 2.1628293e-06, 2.3093253e-05, 4.2100023e-03,
        6.4037077e-04, 2.0255934e-06],
       [9.9980754e-01, 4.7587275e-08, 2.1919164e-05, 1.6841101e-06,
        1.0326332e-08, 2.4832196e-05, 9.1472975e-05, 4.9789514e-07,
        3.2835689e-07, 5.1774139e-05],
       [1.3562148e-05, 2.2025729e-08, 3.2362870e-05, 3.0106017e-07,
        9.9154377e-01, 6.0762841e-07, 7.5223211e-06, 3.0943040e-05,
        4.3247283e-07, 8.3705401e-03]], dtype=float32)>

# reference

### https://tensorflow.google.cn/tutorials/quickstart/beginner